#!/usr/bin/env python3
"""Physically move memories queued for deletion in the viewer into 'Deleted Memories/'.

Workflow:
  1. In the viewer (Memories Viewer.html) open a memory and click "Delete".
     It is hidden everywhere and queued (stored in your browser).
  2. Open the "Deleted" tab and click "Export deletion list" -> downloads
     'snapmemories-deletions.json'.
  3. Double-click "Apply Deletions.cmd" (which runs this script).

This script reads that JSON, moves each item's files out of 'memories/' and 'thumbs/'
into 'Deleted Memories/' (mirrored subfolders, so restoring is trivial), and rewrites
'viewer/data.js' so the viewer forgets them. Nothing is permanently deleted.

Safe to re-run: already-moved files are skipped. Pure standard library.
"""
import os, sys, json, shutil
from pathlib import Path

ROOT     = Path(__file__).resolve().parent
MEM_DIR  = ROOT / "memories"
THUMBS   = ROOT / "thumbs"
DATA_JS  = ROOT / "viewer" / "data.js"
TRASH    = ROOT / "Deleted Memories"
LIST_NAME = "snapmemories-deletions.json"


def log(*a): print(*a, flush=True)


def find_list():
    """Return the newest snapmemories-deletions.json from likely locations."""
    candidates = [
        ROOT / LIST_NAME,
        TRASH / LIST_NAME,
        Path.home() / "Downloads" / LIST_NAME,
    ]
    existing = [p for p in candidates if p.is_file()]
    if not existing:
        return None
    return max(existing, key=lambda p: p.stat().st_mtime)


def load_ids(path):
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        sys.exit(f"Unexpected format in {path} (expected a JSON array of ids).")
    return [str(x) for x in data]


def move_into(src: Path, dest_dir: Path):
    """Move src into dest_dir, overwriting any existing destination. Returns True if moved."""
    if not src.exists():
        return False
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / src.name
    if dest.exists():
        dest.unlink()
    shutil.move(str(src), str(dest))
    return True


def move_files(ids):
    """Move main/overlay/thumb files for each id. Returns (moved_count, set_of_ids_touched)."""
    moved = 0
    touched = set()
    for key in ids:
        any_for_key = False
        # main file: jpg (photo) or mp4 (video)
        for ext in ("jpg", "mp4"):
            if move_into(MEM_DIR / f"{key}-main.{ext}", TRASH / "memories"):
                moved += 1; any_for_key = True
        # overlay (caption) if present
        if move_into(MEM_DIR / f"{key}-overlay.png", TRASH / "memories"):
            moved += 1; any_for_key = True
        # thumbnail if present
        if move_into(THUMBS / f"{key}.jpg", TRASH / "thumbs"):
            moved += 1; any_for_key = True
        if any_for_key:
            touched.add(key)
    return moved, touched


def rewrite_data_js(ids):
    """Drop records whose 'i' is in ids from viewer/data.js. Returns number removed."""
    if not DATA_JS.is_file():
        log(f"  ! {DATA_JS} not found — skipping data.js update.")
        return 0
    text = DATA_JS.read_text(encoding="utf-8")
    marker = "window.MEMORIES ="
    i = text.find(marker)
    if i == -1:
        log("  ! could not find 'window.MEMORIES =' in data.js — skipping update.")
        return 0
    arr_start = text.find("[", i)
    arr_end = text.rfind("]")
    if arr_start == -1 or arr_end == -1 or arr_end < arr_start:
        log("  ! could not parse the MEMORIES array — skipping update.")
        return 0
    records = json.loads(text[arr_start:arr_end + 1])
    drop = set(ids)
    kept = [r for r in records if r.get("i") not in drop]
    removed = len(records) - len(kept)
    if removed:
        with open(DATA_JS, "w", encoding="utf-8") as f:
            f.write("// Auto-generated by build.py. Local data only; do not share.\n")
            f.write("window.MEMORIES = ")
            json.dump(kept, f, ensure_ascii=False, separators=(",", ":"))
            f.write(";\n")
    return removed


def main():
    list_path = find_list()
    if not list_path:
        log("No 'snapmemories-deletions.json' found.")
        log("In the viewer's Deleted tab, click 'Export deletion list', then run this again.")
        log(f"(Looked in: {ROOT}, {TRASH}, and {Path.home() / 'Downloads'})")
        return
    log(f"Reading deletion list: {list_path}")
    ids = load_ids(list_path)
    if not ids:
        log("The deletion list is empty — nothing to do.")
        return
    log(f"  {len(ids)} memories queued.")

    log(f"Moving files into: {TRASH}")
    moved, touched = move_files(ids)
    skipped = len(ids) - len(touched)
    log(f"  files moved: {moved}   already moved / not found: {skipped} of {len(ids)} memories")

    log("Updating viewer/data.js ...")
    removed = rewrite_data_js(ids)
    log(f"  removed {removed} records from data.js")

    applied = list_path.with_name("snapmemories-deletions.applied.json")
    try:
        if applied.exists():
            applied.unlink()
        list_path.rename(applied)
        log(f"Marked list as processed: {applied.name}")
    except OSError:
        pass

    log("")
    log("Done. The originals are now under 'Deleted Memories/' (not permanently deleted).")
    log("To restore one: move its files from 'Deleted Memories/memories' back into 'memories/',")
    log("then re-run 'python build.py'.")


if __name__ == "__main__":
    main()
